### ISSUE TITLE
UI for devices page, add new device popup, filter option for the table.

### ISSUE THREAD

**Issue by shimaaelhosary** [oceanbuilders/admin-panel#5]

**Comment by scottdear** [comment]
@shimaaelhosary I have a couple of questions/comments.  I would like to get your thoughts, and for you to poke holes in this.  In other words it's OK to say, this is a bad idea because..... That's how we make good software, we decide the best approach based on the problems to solve.  That being said..

1. Are there any design docs on this?
2. Are there any plans for device auto-discovery, if not we should talk about that, e.g. someone plugs in a new device and in the admin interface it shows up auto-magically (word I made up).  In other words new devices just show up without having to be added.
3. Does the admin front end talk mqtt to the mqtt server or to @olagalal 's control/raspberry pi server?  If so we should move to using a REST UI.  All of the mobile app stuff should always talk REST to the back-end unless there is a really compelling reason to do otherwise.

Here is what I'm thinking would be ideal.  Please tell me where you think this won't work.

Devices UI between the admin app and the raspberry pi and cloud.
---------------------------------------------------------------------------

In the admin app, when you want to know what devices are currently available you just make an authenticated HTTPS call to the control service.  You make the same API calls if you are local to the pod or remote (just the hostname changes the URL's /endpoints remain the same.

You then make HTTP calls as follows from the admin app the the control server:

GET /devices - gives you an array of JSON objects that represent all the devices.  A device "type" column in the data can tell you how to display in the UI and what attributes to look for/use, each device will have a unique ID that can be used to address the device.

GET /devices/?type=<device_type> - device_type can be a type or list of types that will be used as a filter on the device list returned.

POST /device - adds a new device

PUT /device/<device_id> - update a particular device

DELETE /device/<device_id> - deletes a device

GET /device/<device_id> - get all the detailed attributes, this gets all the attributes of a given device including attributes and might not be returned in the list.

Let me know your thoughts on all of that.

**Comment by shimaaelhosary** [comment]
Hi @scottdear 

1. I am using only the Figma file that has all the designs for the admin panel and I ask Hendrik first for the final designs before implementing.
2. this point should be discussed, but what I think is when an admin adds a new device we could show a loading indicator until the app/web app makes the http request to add this device in the server, then we display this device in the devices table.
3. Th admin panel talks to @olagalal `s control server through authenticated HTTP requests. 


I already asked @olagalal to prepare some APIs to make HTTP requests to get all devices, add new device, update device, and delete device.... and yes we could have an API to get all the information about a specific device using its id if needed. I am not sure if @olagalal  has created issues for these APIs.

**Comment by scottdear** [comment]
Thanks for the the updates. As for 1. I don't think Hendrik has the final designs but @angiedear will check w/ him to make sure you get that.  Also I would be interested in your input in how you think it should be designed.  Based on the requirements for the admin UI.  I can help w/ this if you are new to design.  This is a "green field" project, which means there is lots of room for everyone's input to architect and design creative solutions to the problems being solved.

If I understand it correctly we are trying to create an interface for Ocean Builders staff to access the seapod, so I think it needs to not only talk to the control server, but probably the web server and the mosquitto mqtt server (maybe), and maybe be able to check log files, reboot the pi, etc.

My thoughts are that the control server will only be available via the ob-webserver.  That way the control server does not need to worry about authentication and other local processes can talk to the control server w/out  having to worry about authenticating.  In other words the ob-webserver becomes the authentication layer.  It will be important though that ob-webserver has calls that map to the control server but also all of the other server on the pi.

As for 2. You are exactly right.  There needs to be lots of dicussions :)  I have a draw.io diagram in the smartpod repository with all the pieces.  I would like to know more about the use case of adding a device.  In other words, what would be the steps involved in adding a device.

1. device is added in the app
2. app sends request to add device to control server
3. control server returns a list of devices that can be added that have not already been added?

I'm not clear that happens at step 3, and how the "add device" request is added. 

For #3 is there an API spec that you are using? I can help created one if needed :)
Also I believe the issue oceanbuilders/ob-raspberrypi-server#3 is open for @olagalal  to get the other end of the connection  you need.  I think she is currently working on some deep link issues with @godslave05 and I moved the control server issue to the top of the list, so @olagalal should get to it after she is done w/ the deep link issue.

**Comment by scottdear** [comment]
@shimaaelhosary before you begin work on this, we will  need to discuss the design.  I'm thinking the Admin UI will not "Add" a device.  A device should show up in the UI when it is connected to the network.  We can talk about how that will work when we discuss the design.  After discussing w/ @diegopau, Hendrick and Grant we will be consolidating the admin and user apps into a single application.  The UI view (either admin or user) will be data driven and will be based on the users roles and permissions assigned to their authenticated user.  I will open a new issue for you to work w/ @godslave05 in getting the code from the Admin UI integrated into the user app, at which point we will deprecate the admin app.   Please feel free to ping me if you have any questions.

**Comment by margo-pm** [comment]
Closing this issue and archiving this repo.
